project: 
  type: website
  output-dir: docs

website:
  title: "My Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "R Coding Exercise"
            href: ./coding_exercise.html
          - text: "Visualization Exercise"
            href: ./visualization_exercise.html
          - text: "Tidy Tuesday Exercise"
            href: ./tidytuesday_exercise.html
          - text: "Tidy Tuesday Exercise 2"
            href: ./tidytuesday_exercise2.html
          - text: "Wrangling Exercise"
            href: ./dataanalysis_exercise.html
      - text: "Flu Analysis"
        menu:
          - text: "Data Wrangling"
            href: ./fluanalysis/code/wrangling.html
          - text: "Data Visualization"
            href: ./fluanalysis/code/exploration.html
          - text: "Model Fitting"
            href: ./fluanalysis/code/fitting.html
          - text: "Machine Learning"
            href: ./fluanalysis/code/machinelearing.html
          - text: "Model Improvement"
            href: ./fluanalysis/code/modeleval.html
      - text: "Term Project"
        menu:
          - text: "Summary"
            href: ./AMRproject/AMRsummary.html
    right:
      - icon: github 
        href: https://github.com/rfranci3/RaquelFrancisco-MADA-portfolio

format:
  html:
    theme: darkly
    highlight: zenburn
    css: styles.css
    toc: FALSE


